import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'ja' | 'en' | 'zh-CN' | 'zh-TW';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ja: {
    'nav.home': 'Home',
    'nav.home.sub': 'ホーム',
    'nav.vision': 'Vision',
    'nav.vision.sub': 'ビジョン',
    'nav.services': 'Services',
    'nav.services.sub': '事業内容',
    'nav.pricing': 'Pricing',
    'nav.pricing.sub': '制作プラン',
    'nav.works': 'Works',
    'nav.works.sub': '制作実績',
    'nav.contact': 'Contact',
    'nav.contact.sub': 'お問い合わせ',
    
    'hero.title': 'Digital Craftsmanship',
    'hero.subtitle': '未来を形にする、デジタル・クリエイティブ。',
    'hero.cta': 'Explore Our Works',
    
    'pricing.title': 'Pricing Plans',
    'pricing.subtitle': '制作プラン',
    'pricing.desc': 'Transparent & Flexible Packages',
    'pricing.plan1.title': 'シンプルデザイン',
    'pricing.plan1.sub': 'Simple Design',
    'pricing.plan1.desc': '創業初期や、まずは名刺代わりのサイトが欲しい方に最適。',
    'pricing.plan1.f1': 'シンプルで洗練されたデザイン',
    'pricing.plan1.f2': 'サーバー代・ドメイン代無料',
    'pricing.plan1.f3': 'ドメインいつでも差し替え可能',
    'pricing.plan1.f4': '保守管理費 0円',
    'pricing.plan1.f5': '永久使用可能',
    'pricing.plan1.f6': '最短48時間で納品・公開',
    'pricing.plan1.f7': '創業初期・スタートアップ向け',
    'pricing.plan2.title': 'スタンダードデザイン',
    'pricing.plan2.sub': 'Standard Design',
    'pricing.plan2.desc': 'ブランドイメージを重視し、より高度な機能を求める方に。',
    'pricing.plan2.f1': '独自のデザインスタイル適用',
    'pricing.plan2.f2': '高級・高速サーバー採用',
    'pricing.plan2.f3': 'SEO最適化（基本設定）',
    'pricing.plan2.f4': 'レスポンシブ完全対応',
    'pricing.plan2.f5': 'お問い合わせフォーム設置',
    'pricing.plan2.f6': 'SNS連携・OGP設定',
    'pricing.plan2.f7': 'ブランド力向上に最適',
    'pricing.plan3.title': 'カスタムデザイン',
    'pricing.plan3.sub': 'Custom Design',
    'pricing.plan3.desc': '細部までこだわり抜いた、世界に一つだけの完全オーダーメイド。',
    'pricing.plan3.f1': '100% 完全オリジナルデザイン',
    'pricing.plan3.f2': 'フルオーダーメイド開発',
    'pricing.plan3.f3': '高度なアニメーション・演出',
    'pricing.plan3.f4': '複雑なシステム連携対応',
    'pricing.plan3.f5': '専属デザイナーによる監修',
    'pricing.plan3.f6': '徹底したパフォーマンス改善',
    'pricing.plan3.f7': '大規模・プロフェッショナル向け',
    'pricing.contact': 'お問い合わせ',
    'pricing.suffix.fixed': '円 (固定)',
    'pricing.suffix.from': '円〜',

    'services.title': 'Our Services',
    'services.subtitle': '事業内容',
    'services.desc': 'Comprehensive Digital Solutions',
    'services.web.title': 'WEB開発',
    'services.web.sub': 'Web Development',
    'services.web.desc': 'ReactやNext.jsなどのモダンなフレームワークを使用した、スケーラブルで高性能なWebアプリケーション。',
    'services.ec.title': 'EC構築',
    'services.ec.sub': 'E-Commerce',
    'services.ec.desc': '売上を向上させるカスタムECソリューション。Shopifyのカスタマイズからフルスタック構築まで。',
    'services.ui.title': 'UIデザイン',
    'services.ui.sub': 'UI/UX Design',
    'services.ui.desc': 'ブランドアイデンティティを高める、直感的で美しいユーザーインターフェースの構築。',
    'services.game.title': 'ゲーム開発',
    'services.game.sub': 'Game Development',
    'services.game.desc': 'UnityやモダンなWebGL技術で構築された、没入感のあるインタラクティブな体験とWebベースのゲーム。',
    'services.dx.title': '業務DX支援',
    'services.dx.sub': 'System Optimization',
    'services.dx.desc': 'レガシーシステムの近代化と、既存のビジネスワークフローの最適化による効率の最大化。',
    'services.mobile.title': 'アプリ開発',
    'services.mobile.sub': 'Mobile Application',
    'services.mobile.desc': 'シームレスなユーザーエンゲージメントのために設計された、ネイティブおよびクロスプラットフォームのモバイルアプリ。',
    'services.view_demo': 'デモを見る',

    'contact.title': 'Contact Us',
    'contact.subtitle': 'お問い合わせ',
    'contact.desc': 'Let\'s Create Something Extraordinary',
    'contact.info': 'Contact Information',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.wechat': 'WeChat',
    'contact.hours': '平日 10:00 - 18:00',
    'contact.response': '24時間受付 / 順次対応',
    'contact.new_projects': 'For New Projects',
    'contact.new_projects_desc': 'Web制作、システム開発、DX支援など、デジタル領域の課題解決についてお気軽にご相談ください。<br/><br/>現在、多数のご依頼をいただいており、新規のご相談はメールにて承っております。',
    'contact.send_email': 'Send Email',
    'vision.who': 'Who is Onisaki?',
    'vision.title': 'Not a Demon.<br/>Just A Visionary.',
    'vision.desc1': 'The name "Onisaki" isn\'t about myths; it\'s about the founder\'s promise to deliver relentless quality. Based in Ginza, we are a collective of digital artisans building the next generation of web experiences.',
    'vision.desc2': 'We reject the boring and the standard. From high-conversion EC sites to breathtaking UI designs, we infuse color, motion, and life into every pixel.',
    'vision.tag1': 'CREATIVITY',
    'vision.tag2': 'TECHNOLOGY',
    'vision.tag3': 'PASSION',
    'works.title': 'Works',
    'works.subtitle': '制作実績',
    'works.desc': 'Selected Digital Experiences',
    'works.view_project': 'View Project',
    'footer.tagline': 'Empowering businesses through future-proof digital solutions.',
    'footer.services': 'Services',
    'footer.company': 'Company',
    'footer.resources': 'Resources',
    'footer.office': 'Office',
    'footer.careers': 'Careers',
    'footer.process': 'ご依頼の流れ',
    'footer.legal': '特定商取引法に基づく表記',
    'footer.privacy': 'プライバシーポリシー',
  },
  en: {
    'nav.home': 'Home',
    'nav.home.sub': 'HOME',
    'nav.vision': 'Vision',
    'nav.vision.sub': 'VISION',
    'nav.services': 'Services',
    'nav.services.sub': 'SERVICES',
    'nav.pricing': 'Pricing',
    'nav.pricing.sub': 'PRICING',
    'nav.works': 'Works',
    'nav.works.sub': 'WORKS',
    'nav.contact': 'Contact',
    'nav.contact.sub': 'CONTACT',

    'hero.title': 'Digital Craftsmanship',
    'hero.subtitle': 'Shaping the future through digital creativity.',
    'hero.cta': 'Explore Our Works',

    'pricing.title': 'Pricing Plans',
    'pricing.subtitle': 'PRICING',
    'pricing.desc': 'Transparent & Flexible Packages',
    'pricing.plan1.title': 'Simple Design',
    'pricing.plan1.sub': 'Entry Level',
    'pricing.plan1.desc': 'Perfect for startups or those who need a professional online business card.',
    'pricing.plan1.f1': 'Simple & sophisticated design',
    'pricing.plan1.f2': 'Free server & domain',
    'pricing.plan1.f3': 'Domain can be replaced anytime',
    'pricing.plan1.f4': 'Zero maintenance fees',
    'pricing.plan1.f5': 'Lifetime usage',
    'pricing.plan1.f6': 'Delivery in 48 hours',
    'pricing.plan1.f7': 'Ideal for startups',
    'pricing.plan2.title': 'Standard Design',
    'pricing.plan2.sub': 'Professional',
    'pricing.plan2.desc': 'Focus on brand image with advanced features and performance.',
    'pricing.plan2.f1': 'Unique design style',
    'pricing.plan2.f2': 'High-speed premium server',
    'pricing.plan2.f3': 'Basic SEO optimization',
    'pricing.plan2.f4': 'Fully responsive design',
    'pricing.plan2.f5': 'Contact form integration',
    'pricing.plan2.f6': 'SNS & OGP setup',
    'pricing.plan2.f7': 'Perfect for brand growth',
    'pricing.plan3.title': 'Custom Design',
    'pricing.plan3.sub': 'Enterprise',
    'pricing.plan3.desc': 'One-of-a-kind bespoke solution with attention to every detail.',
    'pricing.plan3.f1': '100% original design',
    'pricing.plan3.f2': 'Full bespoke development',
    'pricing.plan3.f3': 'Advanced animations',
    'pricing.plan3.f4': 'Complex system integration',
    'pricing.plan3.f5': 'Dedicated designer supervision',
    'pricing.plan3.f6': 'Maximum performance tuning',
    'pricing.plan3.f7': 'For large scale projects',
    'pricing.contact': 'Inquiry',
    'pricing.suffix.fixed': 'JPY (Fixed)',
    'pricing.suffix.from': 'JPY ~',

    'services.title': 'Our Services',
    'services.subtitle': 'SERVICES',
    'services.desc': 'Comprehensive Digital Solutions',
    'services.web.title': 'Web Development',
    'services.web.sub': 'WEB DEV',
    'services.web.desc': 'Scalable, high-performance web applications using modern frameworks like React and Next.js.',
    'services.ec.title': 'E-Commerce',
    'services.ec.sub': 'EC SOLUTIONS',
    'services.ec.desc': 'Custom EC solutions that drive sales. From Shopify customization to full-stack builds.',
    'services.ui.title': 'UI/UX Design',
    'services.ui.sub': 'DESIGN',
    'services.ui.desc': 'Crafting intuitive and beautiful user interfaces that elevate your brand identity.',
    'services.game.title': 'Game Development',
    'services.game.sub': 'INTERACTIVE',
    'services.game.desc': 'Immersive interactive experiences and web-based games built with Unity and modern WebGL tech.',
    'services.dx.title': 'System Optimization',
    'services.dx.sub': 'DX SUPPORT',
    'services.dx.desc': 'Modernizing legacy systems and optimizing existing business workflows for maximum efficiency.',
    'services.mobile.title': 'Mobile Application',
    'services.mobile.sub': 'APP DEV',
    'services.mobile.desc': 'Native and cross-platform mobile apps designed for seamless user engagement.',
    'services.view_demo': 'View Demo',

    'contact.title': 'Contact Us',
    'contact.subtitle': 'CONTACT',
    'contact.desc': 'Let\'s Create Something Extraordinary',
    'contact.info': 'Contact Information',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.wechat': 'WeChat',
    'contact.hours': 'Mon-Fri 10:00 - 18:00',
    'contact.response': '24/7 Support / Sequential Response',
    'contact.new_projects': 'For New Projects',
    'contact.new_projects_desc': 'Please feel free to contact us regarding digital solutions such as Web production, system development, and DX support.<br/><br/>Currently, we are receiving many requests, and new consultations are accepted via email.',
    'contact.send_email': 'Send Email',
    'vision.who': 'Who is Onisaki?',
    'vision.title': 'Not a Demon.<br/>Just A Visionary.',
    'vision.desc1': 'The name "Onisaki" isn\'t about myths; it\'s about the founder\'s promise to deliver relentless quality. Based in Ginza, we are a collective of digital artisans building the next generation of web experiences.',
    'vision.desc2': 'We reject the boring and the standard. From high-conversion EC sites to breathtaking UI designs, we infuse color, motion, and life into every pixel.',
    'vision.tag1': 'CREATIVITY',
    'vision.tag2': 'TECHNOLOGY',
    'vision.tag3': 'PASSION',
    'works.title': 'Works',
    'works.subtitle': 'WORKS',
    'works.desc': 'Selected Digital Experiences',
    'works.view_project': 'View Project',
    'footer.tagline': 'Empowering businesses through future-proof digital solutions.',
    'footer.services': 'Services',
    'footer.company': 'Company',
    'footer.resources': 'Resources',
    'footer.office': 'Office',
    'footer.careers': 'Careers',
    'footer.process': 'Process',
    'footer.legal': 'Legal Notice',
    'footer.privacy': 'Privacy Policy',
  },
  'zh-CN': {
    'nav.home': '首页',
    'nav.home.sub': 'HOME',
    'nav.vision': '愿景',
    'nav.vision.sub': 'VISION',
    'nav.services': '业务内容',
    'nav.services.sub': 'SERVICES',
    'nav.pricing': '制作套餐',
    'nav.pricing.sub': 'PRICING',
    'nav.works': '制作案例',
    'nav.works.sub': 'WORKS',
    'nav.contact': '联系我们',
    'nav.contact.sub': 'CONTACT',

    'hero.title': '数字匠心',
    'hero.subtitle': '用数字创意塑造未来。',
    'hero.cta': '浏览案例',

    'pricing.title': '制作套餐',
    'pricing.subtitle': '套餐展示',
    'pricing.desc': '透明且灵活的方案选择',
    'pricing.plan1.title': '简约设计套餐',
    'pricing.plan1.sub': '入门级',
    'pricing.plan1.desc': '适合创业初期，或需要专业电子名片网站的客户。',
    'pricing.plan1.f1': '简约且精美的设计',
    'pricing.plan1.f2': '免费服务器与域名',
    'pricing.plan1.f3': '域名可随时更换',
    'pricing.plan1.f4': '零后续维护费',
    'pricing.plan1.f5': '永久使用',
    'pricing.plan1.f6': '最快48小时交付上线',
    'pricing.plan1.f7': '创业初期首选',
    'pricing.plan2.title': '标准设计套餐',
    'pricing.plan2.sub': '专业级',
    'pricing.plan2.desc': '注重品牌形象，追求更高性能与功能。',
    'pricing.plan2.f1': '独特的设计风格',
    'pricing.plan2.f2': '采用高速高级服务器',
    'pricing.plan2.f3': '基础SEO优化',
    'pricing.plan2.f4': '全平台响应式设计',
    'pricing.plan2.f5': '集成联系表单',
    'pricing.plan2.f6': 'SNS与OGP社交媒体设置',
    'pricing.plan2.f7': '助力品牌成长',
    'pricing.plan3.title': '定制设计套餐',
    'pricing.plan3.sub': '企业级',
    'pricing.plan3.desc': '追求极致细节，独一无二的完全定制方案。',
    'pricing.plan3.f1': '100% 原创设计',
    'pricing.plan3.f2': '全功能定制开发',
    'pricing.plan3.f3': '高级动效与视觉演出',
    'pricing.plan3.f4': '复杂系统集成对接',
    'pricing.plan3.f5': '资深设计师全程监修',
    'pricing.plan3.f6': '极致性能调优',
    'pricing.plan3.f7': '适用于大型专业项目',
    'pricing.contact': '立即咨询',
    'pricing.suffix.fixed': '日元 (固定)',
    'pricing.suffix.from': '日元起',

    'services.title': '业务内容',
    'services.subtitle': '服务项目',
    'services.desc': '全方位的数字解决方案',
    'services.web.title': 'Web开发',
    'services.web.sub': 'WEB开发',
    'services.web.desc': '使用React、Next.js等现代框架构建的高性能、可扩展的Web应用。',
    'services.ec.title': '电商构建',
    'services.ec.sub': 'EC解决方案',
    'services.ec.desc': '助力销售增长的定制电商方案。涵盖从Shopify定制到全栈开发。',
    'services.ui.title': 'UI/UX设计',
    'services.ui.sub': '界面设计',
    'services.ui.desc': '打造直观且精美的用户界面，提升您的品牌价值。',
    'services.game.title': '游戏开发',
    'services.game.sub': '互动体验',
    'services.game.desc': '基于Unity与现代WebGL技术构建的沉浸式互动体验与网页游戏。',
    'services.dx.title': '业务DX支持',
    'services.dx.sub': '系统优化',
    'services.dx.desc': '旧系统现代化升级，优化现有业务流程以实现效率最大化。',
    'services.mobile.title': '移动应用',
    'services.mobile.sub': 'APP开发',
    'services.mobile.desc': '专为无缝用户参与而设计的原生及跨平台移动应用。',
    'services.view_demo': '查看演示',

    'contact.title': '联系我们',
    'contact.subtitle': '咨询通道',
    'contact.desc': '让我们共同创造卓越',
    'contact.info': '联系信息',
    'contact.address': '地址',
    'contact.phone': '电话',
    'contact.email': '邮箱',
    'contact.wechat': '微信',
    'contact.hours': '工作日 10:00 - 18:00',
    'contact.response': '24小时接收 / 依次回复',
    'contact.new_projects': '关于新项目',
    'contact.new_projects_desc': '关于Web制作、系统开发、DX支持等数字领域的解决方案，欢迎随时咨询。<br/><br/>目前咨询量较大，新项目的咨询请通过邮件联系。',
    'contact.send_email': '发送邮件',
    'contact.name': '姓名',
    'contact.subject': '主题',
    'contact.message': '留言内容',
    'contact.send': '提交咨询',
    'contact.sending': '提交中...',
    'contact.success': '留言已成功发送。',
    'contact.error': '发送失败，请稍后重试。',
    'footer.tagline': '通过面向未来的数字解决方案赋能企业。',
    'footer.services': '服务项目',
    'footer.company': '公司信息',
    'footer.resources': '资源中心',
    'footer.office': '办公地址',
    'footer.careers': '加入我们',
    'footer.process': '服务流程',
    'footer.legal': '法律声明',
    'footer.privacy': '隐私政策',
  },
  'zh-TW': {
    'nav.home': '首頁',
    'nav.home.sub': 'HOME',
    'nav.vision': '願景',
    'nav.vision.sub': 'VISION',
    'nav.services': '業務內容',
    'nav.services.sub': 'SERVICES',
    'nav.pricing': '製作套餐',
    'nav.pricing.sub': 'PRICING',
    'nav.works': '製作案例',
    'nav.works.sub': 'WORKS',
    'nav.contact': '聯繫我們',
    'nav.contact.sub': 'CONTACT',

    'hero.title': '數字匠心',
    'hero.subtitle': '用數字創意塑造未來。',
    'hero.cta': '瀏覽案例',

    'pricing.title': '製作套餐',
    'pricing.subtitle': '套餐展示',
    'pricing.desc': '透明且靈活的方案選擇',
    'pricing.plan1.title': '簡約設計套餐',
    'pricing.plan1.sub': '入門級',
    'pricing.plan1.desc': '適合創業初期，或需要專業電子名片網站的客戶。',
    'pricing.plan1.f1': '簡約且精美的設計',
    'pricing.plan1.f2': '免費伺服器與域名',
    'pricing.plan1.f3': '域名可隨時更換',
    'pricing.plan1.f4': '零後續維護費',
    'pricing.plan1.f5': '永久使用',
    'pricing.plan1.f6': '最快48小時交付上線',
    'pricing.plan1.f7': '創業初期首選',
    'pricing.plan2.title': '標準設計套餐',
    'pricing.plan2.sub': '專業級',
    'pricing.plan2.desc': '注重品牌形象，追求更高性能與功能。',
    'pricing.plan2.f1': '獨特的设计風格',
    'pricing.plan2.f2': '採用高速高級伺服器',
    'pricing.plan2.f3': '基礎SEO優化',
    'pricing.plan2.f4': '全平台響應式設計',
    'pricing.plan2.f5': '集成聯繫表單',
    'pricing.plan2.f6': 'SNS與OGP社交媒體設置',
    'pricing.plan2.f7': '助力品牌成長',
    'pricing.plan3.title': '定制設計套餐',
    'pricing.plan3.sub': '企業級',
    'pricing.plan3.desc': '追求極致細節，獨一無二的完全定制方案。',
    'pricing.plan3.f1': '100% 原創設計',
    'pricing.plan3.f2': '全功能定制開發',
    'pricing.plan3.f3': '高級動效與視覺演出',
    'pricing.plan3.f4': '複雜系統集成對接',
    'pricing.plan3.f5': '資深設計師全程監修',
    'pricing.plan3.f6': '極致性能調優',
    'pricing.plan3.f7': '適用於大型專業項目',
    'pricing.contact': '立即諮詢',
    'pricing.suffix.fixed': '日圓 (固定)',
    'pricing.suffix.from': '日圓起',

    'services.title': '業務內容',
    'services.subtitle': '服務項目',
    'services.desc': '全方位的數字解決方案',
    'services.web.title': 'Web開發',
    'services.web.sub': 'WEB開發',
    'services.web.desc': '使用React、Next.js等現代框架構建的高性能、可擴展的Web應用。',
    'services.ec.title': '電商構建',
    'services.ec.sub': 'EC解決方案',
    'services.ec.desc': '助力銷售增長的定制電商方案。涵蓋從Shopify定制到全棧開發。',
    'services.ui.title': 'UI/UX設計',
    'services.ui.sub': '界面設計',
    'services.ui.desc': '打造直觀且精美的用戶界面，提升您的品牌價值。',
    'services.game.title': '遊戲開發',
    'services.game.sub': '互動體驗',
    'services.game.desc': '基於Unity與現代WebGL技術構建的沉浸式互動體驗與網頁遊戲。',
    'services.dx.title': '業務DX支持',
    'services.dx.sub': '系統優化',
    'services.dx.desc': '舊系統現代化升級，優化現有業務流程以實現效率最大化。',
    'services.mobile.title': '移動應用',
    'services.mobile.sub': 'APP開發',
    'services.mobile.desc': '專為無縫用戶參與而設計的原生及跨平台移動應用。',
    'services.view_demo': '查看演示',

    'contact.title': '聯繫我們',
    'contact.subtitle': '諮詢通道',
    'contact.desc': '讓我們共同創造卓越',
    'contact.info': '聯繫信息',
    'contact.address': '地址',
    'contact.phone': '電話',
    'contact.email': '信箱',
    'contact.wechat': '微信',
    'contact.hours': '工作日 10:00 - 18:00',
    'contact.response': '24小時接收 / 依次回覆',
    'contact.new_projects': '關於新項目',
    'contact.new_projects_desc': '關於Web製作、系統開發、DX支持等數字領域的解決方案，歡迎隨時諮詢。<br/><br/>目前諮詢量較大，新項目的諮詢請通過郵件聯繫。',
    'contact.send_email': '發送郵件',
    'contact.name': '姓名',
    'contact.subject': '主題',
    'contact.message': '留言內容',
    'contact.send': '提交諮詢',
    'contact.sending': '提交中...',
    'contact.success': '留言已成功發送。',
    'contact.error': '發送失敗，請稍後重試。',
    'footer.tagline': '通過面向未來的數字解決方案賦能企業。',
    'footer.services': '服務項目',
    'footer.company': '公司信息',
    'footer.resources': '資源中心',
    'footer.office': '辦公地址',
    'footer.careers': '加入我們',
    'footer.process': '服務流程',
    'footer.legal': '法律聲明',
    'footer.privacy': '隱私政策',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    if (saved && (saved === 'ja' || saved === 'en' || saved === 'zh-CN' || saved === 'zh-TW')) {
      return saved as Language;
    }
    // Default to browser language or ja
    const browserLang = navigator.language;
    if (browserLang.startsWith('zh-CN')) return 'zh-CN';
    if (browserLang.startsWith('zh-TW') || browserLang.startsWith('zh-HK')) return 'zh-TW';
    if (browserLang.startsWith('en')) return 'en';
    return 'ja';
  });

  useEffect(() => {
    localStorage.setItem('app-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || translations['ja'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
